version: '3'

services:
  proxy:
    build: .
    ports:
      - "443:443"
    volumes:
      - ./ssl:/app/ssl
    depends_on:
      - backend

  backend:
    build:
      context: .
    image : go_backend
    expose:
      - "8000"
    depends_on : 
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: StrongP@ssw0rd2024
      MYSQL_DATABASE: test_database
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db-password


