version: '3'

services:
  proxy:
    build: nginx/
    image: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - ./ssl:/app/ssl
    depends_on:
      - backend

  backend:
    build: .
    image : backend
    expose:
      - "8000"
    depends_on : 
      - db
    secrets:
      - db-password

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: StrongP@ssw0rd2024
      MYSQL_DATABASE: example
    volumes:
      - db_data:/var/lib/mysql
    
secrets:
  db-password:
    file: db-password
volumes:
  db_data:




